# Generated by Django 4.1 on 2022-09-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_information', models.JSONField(default={})),
                ('network', models.JSONField(default={})),
                ('disk', models.JSONField(default={})),
                ('memory', models.JSONField(default={})),
                ('cpu', models.JSONField(default={})),
                ('load_average', models.JSONField(default={})),
                ('battery_charge_percentage', models.JSONField(default={})),
                ('AC_power', models.JSONField(default={})),
            ],
        ),
    ]
