# Generated by Django 4.1 on 2022-09-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_additionalinformation_ac_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinformation',
            name='disk',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='network',
            field=models.JSONField(default=list),
        ),
    ]
